const v = {
  statusCode: 100,
  body: {
    deviceList: [
      {
        deviceId: "441793102387",
        deviceName: "和室エアコンプラグ",
        deviceType: "Plug",
        enableCloudService: true,
        hubDeviceId: "",
      },
      {
        deviceId: "4417931043E2",
        deviceName: "居間サーキュレータープラグ",
        deviceType: "Plug",
        enableCloudService: true,
        hubDeviceId: "",
      },
      {
        deviceId: "84F703A980B6",
        deviceName: "和室電球側位",
        deviceType: "Color Bulb",
        enableCloudService: false,
        hubDeviceId: "000000000000",
      },
      {
        deviceId: "84F703AE00CE",
        deviceName: "和室電球定位",
        deviceType: "Color Bulb",
        enableCloudService: false,
        hubDeviceId: "000000000000",
      },
      {
        deviceId: "84F703AE5BB6",
        deviceName: "洋室電球定位",
        deviceType: "Color Bulb",
        enableCloudService: false,
        hubDeviceId: "000000000000",
      },
      {
        deviceId: "84F703B2F39A",
        deviceName: "洋室電球側位",
        deviceType: "Color Bulb",
        enableCloudService: false,
        hubDeviceId: "000000000000",
      },
      {
        deviceId: "98CDACB2D25A",
        deviceName: "和室加湿機",
        deviceType: "Humidifier",
        enableCloudService: true,
        hubDeviceId: "000000000000",
      },
      {
        deviceId: "98CDACB384A6",
        deviceName: "居間加湿器",
        deviceType: "Humidifier",
        enableCloudService: true,
        hubDeviceId: "000000000000",
      },
      {
        deviceId: "A848FADC683A",
        deviceName: "居間手元照明",
        deviceType: "Plug",
        enableCloudService: true,
        hubDeviceId: "",
      },
      {
        deviceId: "A848FAE37612",
        deviceName: "こたつ",
        deviceType: "Plug",
        enableCloudService: true,
        hubDeviceId: "",
      },
      {
        deviceId: "A848FAE37CF9",
        deviceName: "和室サーキュレータープラグ",
        deviceType: "Plug",
        enableCloudService: true,
        hubDeviceId: "",
      },
      {
        deviceId: "C4020D28FE91",
        deviceName: "和室",
        deviceType: "Hub Mini",
        enableCloudService: false,
        hubDeviceId: "000000000000",
      },
      {
        deviceId: "D39B53E6FDAA",
        deviceName: "屋外温湿度計",
        deviceType: "Meter",
        enableCloudService: true,
        hubDeviceId: "FBD6EB58069A",
      },
      {
        deviceId: "E11072DCEBFE",
        deviceName: "居間開閉",
        deviceType: "Contact Sensor",
        enableCloudService: true,
        hubDeviceId: "C4020D28FE91",
      },
      {
        deviceId: "E7215D155F95",
        deviceName: "居間温湿度計",
        deviceType: "Meter",
        enableCloudService: true,
        hubDeviceId: "C4020D28FE91",
      },
      {
        deviceId: "EA452FE1FA07",
        deviceName: "和室温湿度計",
        deviceType: "Meter",
        enableCloudService: true,
        hubDeviceId: "C4020D28FE91",
      },
      {
        deviceId: "EB234EE583AE",
        deviceName: "キッチン照明",
        deviceType: "Bot",
        enableCloudService: true,
        hubDeviceId: "C4020D28FE91",
      },
      {
        deviceId: "EB8D5E3DFA74",
        deviceName: "洋室温湿度計",
        deviceType: "Meter",
        enableCloudService: true,
        hubDeviceId: "FBD6EB58069A",
      },
      {
        deviceId: "F3DB8402A78F",
        deviceName: "ドアロック",
        deviceType: "Smart Lock",
        enableCloudService: true,
        hubDeviceId: "FBD6EB58069A",
        master: true,
      },
      {
        deviceId: "F90D9B26BC4B",
        deviceName: "居間照明",
        deviceType: "Bot",
        enableCloudService: true,
        hubDeviceId: "C4020D28FE91",
      },
      {
        deviceId: "FBD6EB58069A",
        deviceName: "洋室",
        deviceType: "Hub Mini",
        hubDeviceId: "000000000000",
      },
    ],
    infraredRemoteList: [
      {
        deviceId: "01-202201081420-44258596",
        deviceName: "和室エアコン",
        remoteType: "Air Conditioner",
        hubDeviceId: "C4020D28FE91",
      },
      {
        deviceId: "01-202201090727-61788295",
        deviceName: "和室サーキュレーター",
        remoteType: "DIY Fan",
        hubDeviceId: "C4020D28FE91",
      },
      {
        deviceId: "02-202201301913-67594303",
        deviceName: "洋室エアコン",
        remoteType: "Air Conditioner",
        hubDeviceId: "FBD6EB58069A",
      },
    ],
  },
  message: "success",
}
